_version: 1.0

Discord:
  # setup bot
  bot-token: ""
  command_prefix: "!"
  intents:
    auto_detect: False
    # Auto-detection only works when the module declares an intent.
    # If you enable the auto-detect feature, you don't need to worry about the settings below.
    guilds: True
    members: True
    moderation: True
    emojis_and_stickers: True
    integrations: True
    webhooks: True
    invites: True
    voice_states: True
    presences: True
    guild_messages: True
    guild_reactions: True
    guild_typing: True
    message_content: True
    guild_scheduled_events: True
    auto_moderation_configuration: True
    auto_moderation_execution: True
    polls: True

Logger:
  debug: True