name: safety.yml
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  safety_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          pip install safety
      - name: safety check
        run: |
          safety check -r requirements.txt